// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EUghpxnpCDNcLYa3SLZ0Q6ayymKVdmY',
    appId: '1:1026523528670:web:94cdab9b2ec5368eecf14f',
    messagingSenderId: '1026523528670',
    projectId: 'walmart-8e4e5',
    authDomain: 'walmart-8e4e5.firebaseapp.com',
    storageBucket: 'walmart-8e4e5.appspot.com',
    measurementId: 'G-GVHSLZWKR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnRtq4vNRQ0mSv0ElYGSK2f4dfv9TgvU',
    appId: '1:1026523528670:android:c95edfde816df1efecf14f',
    messagingSenderId: '1026523528670',
    projectId: 'walmart-8e4e5',
    storageBucket: 'walmart-8e4e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAicmJ6sa3Wp8Atz96Rpx57XxEOZOqGjjk',
    appId: '1:1026523528670:ios:2714d60ecf47e6a5ecf14f',
    messagingSenderId: '1026523528670',
    projectId: 'walmart-8e4e5',
    storageBucket: 'walmart-8e4e5.appspot.com',
    iosBundleId: 'com.example.walmart',
  );
}
